language: go

go:
  - 1.9

before_install:
  - go get -u golang.org/x/lint/golint

script:
  - go test -v &&
    go vet &&
    golint -set_exit_status &&
    scripts/check_gofmt.sh

notifications:
  email:
    on_success: never
