apiVersion: v1
kind: Service
metadata:
  name: passages-signup
  labels:
    name: passages-signup
spec:
  ports:
  - port: 8082
    protocol: TCP
  selector:
    name: passages-signup
  type: NodePort
