apiVersion: v1
kind: Service
metadata:
  name: unified-ingress
  annotations:
    # service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    # service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    # service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: passages-signup
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8082
