name: passages-signup CI

on:
  pull_request:
  push:
  schedule:
    # once a day at 08:00
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      GOPATH: "/home/runner/work/passages-signup/go"

    services:
      postgres:
        image: postgres:12.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Install Golint
        run: go get -u golang.org/x/lint/golint

      - name: Install tooling from Apt
        # Postgres runs in a container, but we also need the client-side
        # tooling.
        run: sudo apt-get install postgresql

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/brandur/passages-signup

      - name: Debug
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "pwd=$(pwd)"
          echo "HOME=${HOME}"
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          echo "GOPATH=${GOPATH}"
          echo "GOROOT=${GOROOT}"

      - name: Install
        run: go install

      - name: "Create database: passages-signup-test"
        run: createdb passages-signup-test
        env:
          PGHOST: localhost
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres

      - name: "Raise database schema"
        run: psql passages-signup-test < schema.sql
        env:
          PGHOST: localhost
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres

      - name: Test
        run: go test -v
        env:
          PGHOST: localhost
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres

      - name: "Check: Gofmt"
        run: scripts/check_gofmt.sh

      - name: "Check: Golint"
        run: "$GOPATH/bin/golint -set_exit_status"

  image-push-docker-hub:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: brandur/passages-signup
          username: ${{ secrets.DockerHubUsername }}
          password: ${{ secrets.DockerHubPassword }}

  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: "Copy .tfvars"
        run: cp terraform/terraform.tfvars.sample terraform/terraform.tfvars

      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "./terraform"

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "./terraform"

      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "./terraform"

      # Requires working CloudFlare/Digital Ocean keys.
      # - name: "Terraform Plan"
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: "latest"
      #     tf_actions_subcommand: "plan"
      #     tf_actions_working_dir: "./terraform"
