name: passages-signup CI

env:
  GO_VERSION: 1.19

on:
  pull_request:
  push:
  schedule:
    # once a day at 08:00
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    services:
      postgres:
        image: postgres:12.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: ${{ env.GO_VERSION }}

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "go env GOPATH=$(go env GOPATH)"
          echo "pwd=$(pwd)"
          echo "HOME=${HOME}"
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"

      - name: "Go: Install"
        run: go install

      - name: "Create database: passages-signup-test"
        run: createdb passages-signup-test
        env:
          PGHOST: localhost
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres

      - name: "Raise database schema"
        run: psql passages-signup-test < sql/schema.sql
        env:
          PGHOST: localhost
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres

      - name: "Go: Test"
        run: go test -v ./...
        env:
          PGHOST: localhost
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres

      - name: "Go: Vet"
        run: go vet

      - name: "Check: Gofmt"
        run: scripts/check_gofmt.sh

  deploy-google-cloud-run:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "GCP: Auth"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"

      - name: "GCP: setup-gcloud"
        uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true
          project_id: passages-signup
          version: "latest"

      - name: "GCP: gcloud info"
        run: gcloud info

      - name: "GCP: Publish image"
        run: gcloud builds submit --tag gcr.io/passages-signup/passages-signup

      - name: "GCP: Deploy nanoglyph-signup"
        run: gcloud run deploy --image gcr.io/passages-signup/passages-signup --platform managed --region us-central1 nanoglyph-signup

      - name: "GCP: Deploy passages-signup"
        run: gcloud run deploy --image gcr.io/passages-signup/passages-signup --platform managed --region us-central1 passages-signup

  golangci-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Check: golangci-lint"
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56

  image-push-docker-hub:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Docker Hub: Publish image"
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: brandur/passages-signup
          username: ${{ secrets.DockerHubUsername }}
          password: ${{ secrets.DockerHubPassword }}

  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Copy .tfvars"
        run: cp ./deploy/terraform/terraform.tfvars.sample ./deploy/terraform/terraform.tfvars

      - name: "Terraform: Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "./deploy/terraform"

      - name: "Terraform: Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "./deploy/terraform"

      - name: "Terraform: Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "./deploy/terraform"

      # Requires working CloudFlare/Digital Ocean keys.
      # - name: "Terraform Plan"
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: "latest"
      #     tf_actions_subcommand: "plan"
      #     tf_actions_working_dir: "./deploy/terraform"
